# PostgreSQL

node.set['postgresql']['config'] = {
  'listen_addresses' => '*', 'port' => 5432
}
node.set['postgresql']['password'] = {
  'postgres' => 'md5795b9da941ed8f2fcd98998ec334d29d',
}

include_recipe "postgresql::server"
include_recipe "postgresql::client"

# Generate custom authentication config
file "/etc/postgresql/9.1/main/pg_hba.conf" do
  content <<-END
# Generated by chef cookbook 'pebbles::default'
local  all  all                   trust
host   all  all  127.0.0.1/32     md5
host   all  all  192.168.33.1/32  md5
  END
  owner "postgres"
  group "postgres"
  mode  0600
  action :create
end

# Reload config
service "postgresql" do
  action :reload
end
